Release animal
Ku6epnec/ZombieFarm pull request #11
Opened 2023-02-20 09:54 UTC by MrDoctor-666

2023-02-20 10:08 UTC, AlenaKarp requested changes

2023-02-20 10:08 UTC, AlenaKarp commented on Assets/Scripts/Animal/Release.cs
> +public class Release : MonoBehaviour
Классы = существительные обычно, например, AnimalLiberator

2023-02-20 10:08 UTC, AlenaKarp commented on Assets/Scripts/Animal/Release.cs
> +public class Release : MonoBehaviour
Почекала, тут же у нас просто логика для клетки, тогда мб лучше прям и назвать Cage?

2023-02-20 10:08 UTC, AlenaKarp commented on Assets/Scripts/Animal/Release.cs
> +    [SerializeField] Slider slider;
progressBar?

2023-02-20 10:08 UTC, AlenaKarp commented on Assets/Scripts/Animal/Release.cs
> +        gameObject.SetActive(false);
А не лучше ей прям Destroy делать?

2023-02-20 21:55 UTC, Ku6epnec approved these changes

2023-02-21 06:57 UTC, AlenaKarp approved these changes

2023-02-21 06:57 UTC, merged