ui branch (bars)
Ku6epnec/ZombieFarm pull request #21
Opened 2023-03-26 20:35 UTC by MrDoctor-666

2023-03-27 06:28 UTC, AlenaKarp requested changes

2023-03-27 06:28 UTC, AlenaKarp commented on Assets/Scripts/Animal/LookAt.cs
> +        if (_object == null)
для прототипа - ок, но так делать - плохо
лучше просто перетянуть камеру в инспекторе

2023-03-27 06:28 UTC, AlenaKarp commented on Assets/Scripts/UI/ProgressBar.cs
> +        if (middleLane)
как будто бы хорошо будет привести проект к единому стилю, в том числе и в оформлении условий
кратенькая лекция: короткий код - хорош, но только тогда, когда он хорошо читается
полная конструкция 
if (a == true) 
{
//some code
}  
позволяет сразу понять, что там тру, что мы не проглядели нигде восклицательный знак и всё в этом духе, а скобки позволяют сразу перейти в тело условия, а не выискивать его где-то непривычно-справа от условий
стиль всегда дело вкуса - готова обсуждать и договариваться, лишь бы было красиво и хорошо

2023-03-27 06:28 UTC, AlenaKarp commented on Assets/Scripts/UI/ProgressBar.cs
> +       // middleLane.localScale = new Vector3(0, 1, 1);
- [ ] ъуъ комменты только для информирования о внештатных ситуаций, где без них - никак
старый код - это старый код, вероятность того, что он будет когда-то раскоменчен стремится к нулю, лучше убрать

2023-03-27 06:28 UTC, AlenaKarp commented on Assets/Scripts/UI/ProgressBar.cs
> +            middleLane.sizeDelta = new Vector2(middleLaneWidth, middleLane.rect.height);
см лекцию про ифочки выше

2023-03-27 06:28 UTC, AlenaKarp commented on Assets/Scripts/UI/ProgressBar.cs
> +            //middleLane.localScale = new Vector3(slider.value/necessaryTime, 1, 1);
- [ ]  ъуъ

2023-03-27 20:25 UTC, MrDoctor-666 commented on Assets/Scripts/Animal/LookAt.cs
> +        if (_object == null)
оке, я просто очень сцену не хотела менять
буду знать, спасибо!!

2023-03-28 06:26 UTC, AlenaKarp approved these changes

2023-03-28 06:26 UTC, merged