Update Interaction and battle system
Ku6epnec/ZombieFarm pull request #30
Opened 2023-06-12 04:06 UTC by Ku6epnec

Ветку перед заливом тестил в основном на дневной локации, в ночной может что-то не работать.

2023-06-12 11:11 UTC, AlenaKarp requested changes

2023-06-12 11:11 UTC, AlenaKarp commented on Assets/Art/Prototype/SkythianCat/Hand_Painted_Nature_Kit_LITE/DEMO/Demo_scene.unity
Шо там сохранено на одной сцене и не сохранено на другой? Это бы вынести в Root префаб

2023-06-12 11:11 UTC, AlenaKarp commented on Assets/Scripts/AI/Zombie.cs
> +        private float Maxtimer = 1.0f;
- [x] Можно переименовать Maxtimer в maxTimer?

2023-06-12 11:11 UTC, AlenaKarp commented on Assets/Scripts/AI/Zombie.cs
> +            playerView = FindObjectOfType<ZombieFarm.Views.Player.PlayerView>();
- [x] Сделай на это дело ViewManager, который будет родителем над этими двумя ребятами, в этом менеджере в SerializedField на них ссылки, и публичные методы GetPlayerView() и GetInteractiveArea(), которые будут их возвращать соответственно (и вынести их в интерфейс IViewManager). У нас есть синглтон, который сейчас везде шарит менеджеры - Root. Туда надо будет прописать IViewManager. Таким образом тут не надо будет эти поля, а этих ребят чисто получать через Root.ViewsManager.GetPlayerView() и Root.ViewsManager.GetInteractiveArea(). Если над с этим помощь - пиши

2023-06-12 11:11 UTC, AlenaKarp commented on Assets/Scripts/AI/Zombie.cs
> +        public void RecievedDamage(float damage)
- [x] Received, очепятка

2023-06-12 11:11 UTC, AlenaKarp commented on Assets/Scripts/AI/Zombie.cs
> +            if (recievedDamageTimer <= 0)
- [x] И этой переменной тож опечатка

2023-06-12 11:11 UTC, AlenaKarp commented on Assets/Scripts/Animal/Cage.cs
> +    private float Maxtimer = 2.0f;
maxTimer и received

2023-06-12 11:11 UTC, AlenaKarp commented on Assets/Scripts/Managers/AttackTrigger.cs
> +            playerView = FindObjectOfType<PlayerView>();
Root.ViewsManager.GetPlayerView()

2023-06-12 11:11 UTC, AlenaKarp commented on Assets/Scripts/Managers/AttackTrigger.cs
> +        public Cage cage;
Как будто бы все публичное может спокойно быть приватным. Если оно нужно где-то вне - надо сделать интерфейс и передавать через него через геттер. Плюс можно сделать интерфейс для enemy и cage - IInteractiveObject - и поля InteractiveObject, Enemy и Cage можно будет сократить до одного IInteractiveObject interactiveObject. Зомби ли это или клетка у тебя уже проверяется и передается в триггер энтере

2023-06-12 11:11 UTC, AlenaKarp commented on Assets/Scripts/Managers/AttackTrigger.cs
> +                if (InteractiveObject.TryGetComponent<ZombieFarm.AI.Zombie>(out ZombieFarm.AI.Zombie zombie))
if (other.tag == "Zombie") и if (InteractiveObject.TryGetComponent<ZombieFarm.AI.Zombie>(out ZombieFarm.AI.Zombie zombie)) - масло маслянное, надо оставить что то одно, лучше второе

2023-06-12 11:11 UTC, AlenaKarp commented on Assets/Scripts/Managers/Interfaces/IHaveInventory.cs
Это кажется лишнее?

2023-06-12 11:11 UTC, AlenaKarp commented on Assets/Scripts/Managers/InteractiveArea.cs
> +        private void OnTriggerEnter(Collider other)
У тебя два метода реализуют одно и то же при OnTriggerEnter'e. Это плохо, DRY-принцип, все дела. Я еще не дошла до того куда шарится InteractiveObject, но это есть не очень хорошо. Можно, например передавать их все в виде интерфейса как писала выше, и на стороне приема чекать что это за интерактивный объект и делать с ним дела.

2023-06-12 11:11 UTC, AlenaKarp commented on Assets/Scripts/UI/ProgressBar.cs
> +    private float MaxHealth;
А если это будет прогресс бар не для здоровья? ;3
Мб назвать как-то поуниверсальнее, вроде maxValue? И стиль переменной тоже..

2023-06-12 11:11 UTC, AlenaKarp commented on Assets/Scripts/UI/ProgressBar.cs
> +    public void StartProgress(float damage)
damage тоже лучше переназвать во что-то поуниверсальнее

2023-06-12 11:11 UTC, AlenaKarp commented on Assets/Scripts/Views/Player/PlayerView.cs
> +        public Cage cage;
ъуъ писала про них выше

2023-06-12 11:11 UTC, AlenaKarp commented on Assets/Scripts/Views/Player/PlayerView.cs
> +        public float _health = 20;
Эти в SerializedField, у тебя они выше публично шарятся в интерфейсе, не надо дублировать

2023-06-12 11:11 UTC, AlenaKarp commented on Assets/Scripts/Views/Player/PlayerView.cs
> +        public void OnIdle()
Тут я понимаю оно зачем, править нинада, просто скажу что такой подход не очень хорош. Стейтами плеера должен руководить ток сам плеер, извне их менять кем-угодно плохая практика. (Да, я знаю что так уже сделано, просто если есть возможность так не делать - лучше не делать)

2023-06-12 11:11 UTC, AlenaKarp commented on Assets/Scripts/Views/Player/PlayerView.cs
> +                cage.RecievedDamage(Damage);
А зачем нам промежуточный шаг в виде PlayerView? Почему бы не подписать на это событие сразу клетку и enemy? Мы ж их получаем в TriggerEnter в AttackTrigger'e и InteractiveArea, можно сразу и подписать

2023-06-12 11:11 UTC, AlenaKarp commented on Assets/Scripts/Views/Player/PlayerView.cs
> +        public void RecievedDamage(float damage)
received

2023-06-12 11:11 UTC, AlenaKarp commented on Assets/Scripts/Views/Player/PlayerView.cs
> +            }
лишнее

2023-06-13 11:32 UTC, Ku6epnec commented on Assets/Art/Prototype/SkythianCat/Hand_Painted_Nature_Kit_LITE/DEMO/Demo_scene.unity
Там сохранено в префаб=\ просто когда тестил на сцене вначале закидывал на саму сцену, но в префаб тоже добавил, на сцене так и остался "+" вот он сохранил инфу, "+" удалил, оно само обновилось.

2023-06-13 14:50 UTC, Ku6epnec commented on Assets/Scripts/Managers/InteractiveArea.cs
> +        private void OnTriggerEnter(Collider other)
Решил вопрос при добавлении класса ReceivedDamageObject.

2023-06-13 14:51 UTC, Ku6epnec commented on Assets/Scripts/Views/Player/PlayerView.cs
> +        public Cage cage;
Точно также засунул в ReceivedDamageObject.

2023-06-13 16:12 UTC, Ku6epnec commented on Assets/Scripts/AI/Zombie.cs
> +            playerView = FindObjectOfType<ZombieFarm.Views.Player.PlayerView>();
Сделалъ

2023-06-14 19:31 UTC, AlenaKarp requested changes

2023-06-14 19:31 UTC, AlenaKarp commented on Assets/Scripts/Animal/LookAt.cs
>      [SerializeField] GameObject _object;
А он нам еще нужен как [SerializeField], раз инитится через скрипт. Мб просто заприватить?

2023-06-14 19:31 UTC, AlenaKarp commented on Assets/Scripts/Managers/AttackTrigger.cs
> +        private GameObject InteractiveObject;
Поле теперь приватное - с маленькой буквы

2023-06-14 19:31 UTC, AlenaKarp commented on Assets/Scripts/Managers/AttackTrigger.cs
> +        private ReceivedDamageObject ReceivedDamageObject;
Поле теперь приватное - с маленькой буквы

2023-06-14 19:31 UTC, AlenaKarp commented on Assets/Scripts/Managers/InteractiveArea.cs
> +        private void OnTriggerEnter(Collider other)
А InteractiveObject всё еще public и шарится на сторону. (и lookAt) тоже. Если они нужны как public - надо хотя бы геттеры сделать, но в идеале чтобы они не выставлялись извне.

2023-06-14 21:25 UTC, Ku6epnec commented on Assets/Scripts/Animal/LookAt.cs
>      [SerializeField] GameObject _object;
Неее, у нас эта штука может и в дальнейшем использовать, когда нужно, чтобы кто-то или что-то пырилось на определённый объект и не всегда будет удобно через скрипт делать(особенно для тестов ГД), поэтому пускай будет. У нас же и коза тоже пырится на игрока, а не только игрок на зомби, уверен в дальнейшем ещё будут такие объекты попадаться.

2023-06-26 11:41 UTC, AlenaKarp approved these changes

2023-06-26 11:41 UTC, AlenaKarp commented on Assets/Scripts/Managers/InteractiveArea.cs
> +        internal event Action Interactive = () => { };
Туть тоже OnInteractive

2023-06-26 11:44 UTC, AlenaKarp approved these changes

2023-06-26 11:44 UTC, AlenaKarp commented on Assets/Scripts/Managers/InteractiveArea.cs
> +        private void Cleaner()
Названия методов - глаголы. Clean()

2023-06-26 13:53 UTC, merged