Death and other bug fixes
Ku6epnec/ZombieFarm pull request #42
Opened 2023-07-17 22:17 UTC by MrDoctor-666

2023-07-18 21:09 UTC, AlenaKarp requested changes

2023-07-18 21:09 UTC, AlenaKarp commented on Assets/Scripts/AI/Zombie.cs
> +        [SerializeField] private float attackDistance = 2f;
Проверить сериализованные поля

2023-07-18 21:09 UTC, AlenaKarp commented on Assets/Scripts/Managers/InteractiveArea.cs
> +        public void Clean()
Все паблик методы должны быть накрыты интерфейсами, и вообще не оч хорошо, когда кто-то извне вот прям так подлезает. Если ну прям оч надо - лучше делать через internal, если есть такая возможность

2023-07-18 21:09 UTC, AlenaKarp commented on Assets/Scripts/UI/ProgressBar.cs
> +        SetProgress(lostProgressValue);
Если тут корутина больше не нужна - снеси её из полей и из методе Reset

2023-07-18 21:09 UTC, AlenaKarp commented on Assets/Scripts/UI/ProgressBar.cs
> +        SetProgress(lostProgressValue);
Как будто бы она ток тут сетится

2023-07-18 21:09 UTC, AlenaKarp commented on Assets/Scripts/Views/Player/PlayerView.cs
> +        }
Пошто пустой Awake?

2023-07-19 19:03 UTC, MrDoctor-666 commented on Assets/Scripts/UI/ProgressBar.cs
> +        SetProgress(lostProgressValue);
так я тут и так корутину снесла

2023-07-19 19:27 UTC, MrDoctor-666 commented on Assets/Scripts/AI/Zombie.cs
> +        [SerializeField] private float attackDistance = 2f;
чекнула, там в префабах, кажется, все норм стоит

2023-07-19 19:42 UTC, MrDoctor-666 commented on Assets/Scripts/AI/Zombie.cs
> +        [SerializeField] private float attackDistance = 2f;
было не норм, но я поправила + поправила коллайдеры на зомбях

2023-07-19 19:55 UTC, MrDoctor-666 commented on Assets/Scripts/Managers/InteractiveArea.cs
> +        public void Clean()
сделала пока через internal, надеюсь, норм

2023-07-19 19:55 UTC, MrDoctor-666 commented on Assets/Scripts/Views/Player/PlayerView.cs
> +        }
убрала

2023-07-19 20:38 UTC, AlenaKarp approved these changes

2023-07-19 20:38 UTC, merged