Chests
Ku6epnec/ZombieFarm pull request #43
Opened 2023-07-20 14:05 UTC by MrDoctor-666

2023-07-20 14:33 UTC, AlenaKarp requested changes

2023-07-20 14:33 UTC, AlenaKarp commented on Assets/Scripts/UI/ProgressBar.cs
> +        //slider = GetComponent<Slider>();
комменты кыш

2023-07-20 14:33 UTC, AlenaKarp commented on Assets/Scripts/UI/ProgressBar.cs
>      internal event Action ProcessCompleted = () => { };
Можешь пж переименовать в OnProcessCompleted, а то при подписке на него не поняла, что это Action

2023-07-20 14:33 UTC, AlenaKarp commented on Assets/Scripts/InteractableObjects/OnTriggerInteractionWithVFX.cs
> +            Destroy(gameObject);
Я знаю, что так было, но давай его выключать пж

2023-07-20 14:33 UTC, AlenaKarp commented on Assets/Scripts/UI/ProgressBar.cs
> +            //slider.value += Time.fixedDeltaTime;
и тут кыш

2023-07-20 14:39 UTC, MrDoctor-666 commented on Assets/Scripts/UI/ProgressBar.cs
>      internal event Action ProcessCompleted = () => { };
переименовала

2023-07-20 14:39 UTC, MrDoctor-666 commented on Assets/Scripts/UI/ProgressBar.cs
> +        //slider = GetComponent<Slider>();
убрала

2023-07-20 14:40 UTC, MrDoctor-666 commented on Assets/Scripts/UI/ProgressBar.cs
> +            //slider.value += Time.fixedDeltaTime;
убрала

2023-07-20 14:41 UTC, MrDoctor-666 commented on Assets/Scripts/InteractableObjects/OnTriggerInteractionWithVFX.cs
> +            Destroy(gameObject);
теперь выключается

2023-08-09 18:09 UTC, AlenaKarp approved these changes

2023-08-09 18:10 UTC, merged