Spawn branch(Не вливать!!!)
Ku6epnec/ZombieFarm pull request #46
Opened 2023-08-23 19:40 UTC by Ku6epnec

2023-10-11 16:47 UTC, MrDoctor-666 commented on Assets/Scripts/ConstructionData.cs
> +public class ConstructionData : IConstructionObject, IData
Как поняла, и в IConstructionObject и в IData есть objectName, зачем только? не запутаемся ли мы?

2023-10-11 16:50 UTC, MrDoctor-666 commented on Assets/Scripts/Managers/ViewManager.cs
> +        //_playerView = spawnConfig.PlayerObjects[0].playerView;
коменты непонятные, стоит бы удалить, раз не используем?

2023-10-11 16:51 UTC, MrDoctor-666 commented on Assets/Scripts/PlayerData.cs
> +    public ZombieFarm.Views.Player.PlayerView playerView;
а зачем явное указание пути? нельзя ZombieFarm.Views.Player просто в using кинуть

2023-10-11 16:52 UTC, MrDoctor-666 commented on Assets/Scripts/SceneEditor.cs
> +        Debug.Log("�������� �����������");
ой, у меня этот дебаг как куча закорючек выглядит, лучше убрать, мне кажется

2023-10-11 16:57 UTC, MrDoctor-666 commented on Assets/Scripts/SceneEditor.cs
> +        public Dictionary<string, Transform> EnvironmentDictionary = new Dictionary<string, Transform>();
может, я слепая, но эти словари используются где-нибудь?

2023-10-11 20:40 UTC, AlenaKarp requested changes

2023-10-11 20:40 UTC, AlenaKarp commented on Assets/Prefabs/LoadPrefabs/Constuctions/fence_1 - Copy.prefab
Я так понимаю эти префабы - тестовые для загрузки-выгрузки? Может ну их из проекта, у нас и так там префабов окружения нормально, мешаться будут

2023-10-11 20:40 UTC, AlenaKarp commented on Assets/Scripts/ConstructionData.cs
> +    public Transform constuctionTransform;
constRuction

2023-10-11 20:40 UTC, AlenaKarp commented on Assets/Scripts/ConstructionData.cs
> +    public Transform ObjectTransform => constuctionTransform;
а вот эти поля не сериализуются? я не оч помню но как будто бы все паблик поля сериализуются, а если так, то тут два одинаковых сериализуется

2023-10-11 20:40 UTC, AlenaKarp commented on Assets/Scripts/Managers/Interfaces/IConstructionObject.cs
> +public class IConstructionObject : MonoBehaviour
А не должны ли они быть интерфейсами? название начинающееся с I означает, что ето интерфейс

2023-10-11 20:40 UTC, AlenaKarp commented on Assets/Scripts/ConstructionData.cs
> +public class ConstructionData : IConstructionObject, IData
Я б посоветовала наверное IConstructionObject наследовать IData, потому что как будто бы все эти интерфейсы - это обертка данных по сути

2023-10-11 20:40 UTC, AlenaKarp commented on Assets/Scripts/PlayerData.cs
> +    public Vector3 posit;
...ion
налог на буквы? :))))))

2023-10-11 20:40 UTC, AlenaKarp commented on Assets/Scripts/PlayerData.cs
> +    public ZombieFarm.Views.Player.PlayerView playerView;
а что у нас там в плеер вью вообще, что его сериализовать надо? Обычно View часть - это внешний вид, моделька и всё что с ней связано. в идеале бы её не сериализовывать, а просто спавнить из префаба, как будто бы там единственное что могло бы быть - скины, но и тогда весь объект не нужен

2023-10-11 20:40 UTC, AlenaKarp commented on Assets/Scripts/SceneEditor.cs
> +    private SpawnParameters GetSpawnParameters(string typeObject)
Метод выглядит оч хорошо, ты молодец!

2023-10-11 20:40 UTC, AlenaKarp commented on Assets/Scripts/SceneEditor.cs
> +        string[] StringObjects = jsonContainer.Split("}{");
приватные, локальные поля с маленькой буквы

2023-10-11 20:40 UTC, AlenaKarp commented on Assets/Scripts/SceneEditor.cs
> +            foreach (Transform child in ObjectContainers[containerIndex])
Смотри, вот тут ситуация, когда цикл внутри цикла. Це значит что сложность алгоритмическая квадратичная (если цикл один работает n времени, то вложенный будет работать n*n, сильно дольше). Таких моментов лучше избегать и использовать когда либо ну больше никак, либо в целом пофек на время исполнения. Так как это сейвы, тут наверное ладно, но если просто попадется в фичах, лучше избегать. А написала это я просто для общего ознакомления, почитать - подумать, всё такое. Править наверн не надо

2023-10-11 20:40 UTC, AlenaKarp commented on Assets/Scripts/SceneEditor.cs
> +        Debug.Log("�������� �����������");
дебаги кыш или хотя б не на русском

2023-10-11 20:40 UTC, AlenaKarp commented on Assets/Scripts/SceneEditor.cs
> +        Debug.Log("����� �����: " + childs.Count);
я их больше комментить не буду, но с дебагами вопрос над решить

2023-10-11 20:40 UTC, AlenaKarp commented on Assets/Scripts/SceneEditor.cs
> +        for (int i = 0; i < childs.Count; i++)
при условии, что каждый из типов объектов наследует IData как писали выше это можно записать получше 
```

for (int i = 0; i<childs.Count; i++)
{
    if(TryGetComponent<IData>(out` IData data) == true)
    {
        SaveTypedObject(data);   
    }
}

private void SaveTypedObject(IData data)
{ 
    switch(data)
    {
        case IEnvironmentObject environmentObject:
            SaveEnvironmentObject(environmentObject);
            break;

        case IPlayerObject playerObject:
            SavePlayerObject(playerObject);
            break;
            
            и.т.д.
    }
}
```

2023-10-11 20:40 UTC, AlenaKarp commented on Assets/Scripts/SceneEditor.cs
> +        thisObject.rotation = friendlyObject.transform.rotation;
Смотри, у тебя вот тут поля объектов во всех методах SaveЧетотам повторяются. Вместо этого можно сделать один единственный метод SaveObject у которого изменяются только входные параметры там где мы его вызываем. 

Тут опять же поинт, что IКакойтотамObject накрыт интерфейсом IData.

```
    private void SaveObject(IData data, string objType)
    {
        //тут кст еще загадка зачем нам этот i, он как будто бы больше нигде не юзается, разъясни мб даже тут в комментах зочем оно с циклом тут
        int i = 0;

        while (spawnConfig.ConstructionObjects[i].objectName != obj.objectName && i < spawnConfig.PlayerObjects.Length)
        {
            i++;
        }

        SceneObject thisObject = new SceneObject();

        thisObject.typeObject = objType;
        thisObject.nameObject = data.ObjectName;
        thisObject.position = data.ObjectTransform.position; //тут в интерфейс будет достаточно вынести Transform, отделять позицию и ротацию не надо
        thisObject.rotation = data.ObjectTransform.rotation;
        thisObject.scale = data.ObjectTransform.localScale;

        MainList.Add(thisObject);

        jString += JsonUtility.ToJson(MainList[index]);
        index++; //индекс я тож не поняла к чему тут
    }
```

2023-10-11 20:40 UTC, AlenaKarp commented on Assets/Scripts/SceneEditor.cs
> +        thisObject.rotation = friendlyObject.transform.rotation;
Мысль вторая - может быть и тип (который objType) в IData засунуть, тогда можно будет чисто IData передавать и без всякого стринга

2023-10-11 20:40 UTC, AlenaKarp commented on Assets/Scripts/Spawner.cs
> +public class Spawner : MonoBehaviour
Я бы предложила такой вариант 

и еще заменить поле `spawnSetting.playerView` на `spawnSetting.prefab`, как у остальных что и в контексте логичнее

```
public class Spawner : MonoBehaviour
{
    public static void SpawnAllObjects(SpawnConfig spawnSettings, Transform transform)
    {
        Spawn(spawnSettings.PlayerObjects);
        Spawn(spawnSettings.EnemyObjects);
        Spawn(spawnSettings.FriendlyObjects);
        Spawn(spawnSettings.ConstructionObjects);
        Spawn(spawnSettings.EnvironmentObjects);
    }

    //тут может с интерфейсом не получится, тада возможно надо будет наследовать от одного родителя просто все объекты, подразумевать его вместо IData
    private static void Spawn(IData[] objects)
    {
        foreach (IData obj in objects)
        {
            var pref = Instantiate(obj.prefab, transform);
            pref.transform.position = obj.posit;
        }
    }
}
```

2023-10-16 13:34 UTC, Ku6epnec commented on Assets/Scripts/Managers/Interfaces/IConstructionObject.cs
> +public class IConstructionObject : MonoBehaviour
Полностью убрал I***Object(везде оставил прямое наследование ***Data от IData)

2023-10-16 13:37 UTC, Ku6epnec commented on Assets/Scripts/PlayerData.cs
> +    public Vector3 posit;
Добавил буквы=\ и using ZombieFarm.Views.Player;(для удобства)

2023-10-16 13:51 UTC, Ku6epnec commented on Assets/Scripts/SceneEditor.cs
> +    private SpawnParameters GetSpawnParameters(string typeObject)
1) PlayerData в текущем варианте не используется, т.к. движущиеся объекты мы не спауним, далее этот метод точно будет изменяться и нам нам нужно правильно брать вьюшку, чтобы связи между объектами не терялись.
2) Исправил названия для пересчёта, вместо i и j

2023-10-16 13:54 UTC, Ku6epnec commented on Assets/Scripts/SceneEditor.cs
> +        string[] StringObjects = jsonContainer.Split("}{");
Исправил.

2023-10-16 13:56 UTC, Ku6epnec commented on Assets/Scripts/SceneEditor.cs
> +            foreach (Transform child in ObjectContainers[containerIndex])
Понимаю, такая сложность и должна быть, мы поочерёдно проверяем каждый объект в определённых контейнерах, такой код выглядит наиболее простым способом, а при проверке этой сложности мы не избежим) разницы между сложностью сразу 50 или через двойной цикл 5*10 нет, а записано короче.

2023-10-16 14:02 UTC, Ku6epnec commented on Assets/Scripts/SceneEditor.cs
> +        Debug.Log("�������� �����������");
Убрал большинство дебагов, переименовал парочку, для подтверждения завершения сохранения и загрузки.

2023-10-16 14:02 UTC, Ku6epnec commented on Assets/Scripts/SceneEditor.cs
> +        Debug.Log("����� �����: " + childs.Count);
Решил

2023-10-16 14:19 UTC, Ku6epnec commented on Assets/Scripts/SceneEditor.cs
> +        for (int i = 0; i < childs.Count; i++)
Пробовал переписать подобным образом, так перестаёт работать, видимо дело в попытке перехода из IData в PlayerData и т.д.

2023-10-16 14:20 UTC, Ku6epnec commented on Assets/Scripts/ConstructionData.cs
> +public class ConstructionData : IConstructionObject, IData
I***Object порезал, теперь нет дубля.

2023-10-18 14:24 UTC, Ku6epnec commented on Assets/Scripts/SceneEditor.cs
> +        public Dictionary<string, Transform> EnvironmentDictionary = new Dictionary<string, Transform>();
Действительно, в текущей версии скрипта данный класс уже не используется=\, убрал его.

2023-10-18 14:26 UTC, Ku6epnec commented on Assets/Prefabs/LoadPrefabs/Constuctions/fence_1 - Copy.prefab
Нет, это новая папка LoadPrefabs в которую объединены все префабы, которые на текущий момент используются на локации, т.к. изначально они как раз таки разбросаны в проекте.

2023-10-18 14:27 UTC, Ku6epnec commented on Assets/Scripts/ConstructionData.cs
> +    public Transform constuctionTransform;
исправлено=\

2023-10-18 14:33 UTC, Ku6epnec commented on Assets/Scripts/ConstructionData.cs
> +    public Transform ObjectTransform => constuctionTransform;
Это реализация интерфейса.

2023-10-18 14:45 UTC, Ku6epnec commented on Assets/Scripts/SceneEditor.cs
> +        thisObject.rotation = friendlyObject.transform.rotation;
1) i переназвал, с помощью цикла тут ищем нужный объект в spawnConfig.PlayerObjects(у нас может быть несколько готовых префабов для спауна и тут мы вибарем тот, который нужен прямо сейчас).
2) Получившийся объект мы добавляем в MainList(Общий пул объектов, которые мы сейчас сохраняем), а index используется для смещения дальше по данному пулу и пересчёта количества строк(соответствия числу объектов в пуле)

2023-10-18 14:51 UTC, Ku6epnec commented on Assets/Scripts/Spawner.cs
> +public class Spawner : MonoBehaviour
В данный момент Spawner у нас не используется(ранее нужен был для теста другого метода спауна объектов, до скрипта SceneEditor. Возможно стоит действительно переписать и связать с SceneEditor.

2023-11-01 17:16 UTC, closed without merging