Location transition
Ku6epnec/ZombieFarm pull request #49
Opened 2023-08-30 18:47 UTC by MrDoctor-666

2023-08-30 19:41 UTC, AlenaKarp requested changes

2023-08-30 19:41 UTC, AlenaKarp commented on Assets/Scripts/Interfaces/IUIElement.cs
>  public interface IUIElement
А не лучше ли ему быть IWindow? UIElement - это же типа кнопка, бар какой-нибудь
А то тут прям открыть-закрыть и все дела

2023-08-30 19:41 UTC, AlenaKarp commented on Assets/Scripts/LocationTransition/LocationTransitionArea.cs
> +        [SerializeField] private string uiToOpenID;
Я тупая и не поняла смысола этого поля
Не лучше ли сделать по типу через енам? Плюс панель как будто бы напрямую связана со сценой которую мы планируем открывать, тада почему мы её ручками в префабе задаем, а не в конфиге каком-нибудь?

2023-08-30 19:41 UTC, AlenaKarp commented on Assets/Scripts/Managers/TransitionManager.cs
> +            Debug.Log("UI should be opened");
Дебаги кыш

2023-08-30 19:41 UTC, AlenaKarp commented on Assets/Scripts/Managers/TransitionManager.cs
> +            Debug.Log("Coroutine should be start");
И тут кыш

2023-08-30 19:41 UTC, AlenaKarp commented on Assets/Scripts/Managers/TransitionManager.cs
> +            while (!asyncLoad.isDone)
asyncLoad.isDone == false
я бабка и не вижу в коде эти ваши восклицательные знаки

2023-08-30 19:41 UTC, AlenaKarp commented on Assets/Scripts/Managers/TransitionManager.cs
> +    public class TransitionManager : MonoBehaviour, ITransitionManager
А даваааай назовем его SceneTransitionManager, а то не понятно кого куда транзитят

2023-08-30 20:20 UTC, MrDoctor-666 commented on Assets/Scripts/LocationTransition/LocationTransitionArea.cs
> +        [SerializeField] private string uiToOpenID;
ето вот на это я на себя ругалась, там просто UI менеджер ща хранит словарь ключ-значения аля имя окна, само окно, и открывает по имени тип
я сначала хотел сделать через enum эти ключи, но что-то меня остановило, что не помню, но думаю тут могу на enum-ы поменять
а панель просто открывается как при заупске сцены, так и перед ее запуском (она асинхронно грузится потому что? так? наверное? лучше?)

2023-08-30 20:41 UTC, AlenaKarp commented on Assets/Scripts/LocationTransition/LocationTransitionArea.cs
> +        [SerializeField] private string uiToOpenID;
Сделай прям в UI менеджере енам что-то вроде WindowType, пусть словарь хранит пару тип-окно
Если в сериализованных полях хранятся дефолтные значения для запуска панели перед сценой - пропиши эт в названиях переменных, чтобы было понятно, для чего эти поля

2023-09-06 18:12 UTC, AlenaKarp approved these changes

2023-09-06 18:13 UTC, merged