UI assets
Ku6epnec/ZombieFarm pull request #54
Opened 2023-10-11 14:42 UTC by MrDoctor-666

2023-10-11 14:56 UTC, Ku6epnec approved these changes
Only UI changes, need test on main scene

2023-10-11 18:30 UTC, AlenaKarp requested changes

2023-10-11 18:30 UTC, AlenaKarp commented on Assets/Scripts/UI/ExchangeWindow.cs
> +        [SerializeField] private Image finalGetImage;
Вот эти пары полей в структуру 
```
[Serializable]
public struct Имяструктуры
{  
    public TextMeshProUGUI finalGetAmountText;
    public Image finalGetImage;
}
```

Структуру в SerializeField, и будет два поля вместо четырех, будет хорошо

2023-10-11 18:30 UTC, AlenaKarp commented on Assets/Scripts/UI/ExchangeWindow.cs
> +                        downItem.SetInteractable(false);
Этот if else можно заменить на 

bool условиенейм = foundResource.linkToOtherResource.HasValue == true && foundResource.thisWorth <= upItemSelected.Amount;

downItem.SetInteractable(условиенейм);

2023-10-11 18:30 UTC, AlenaKarp commented on Assets/Scripts/UI/ExchangeWindow.cs
> +                finalSpendImage.sprite = upItemSelected.resourceImage.sprite;
Это дублирование обернуть в метод, в него параметром передавать itemIteration, itemSelected

2023-10-11 18:30 UTC, AlenaKarp commented on Assets/Scripts/UI/ExchangeWindow.cs
> +            finalSpendImage.sprite = null;
см коммент с методом оберткой выше

2023-10-11 18:30 UTC, AlenaKarp commented on Assets/Scripts/UI/ExchangeWindow.cs
> +            amountSelection.GetComponentInChildren<TextMeshProUGUI>().text = (amountSelection.value).ToString();
Вот тут нельзя этот компонент в Awake получить? Если можно то лучше получить

2023-10-11 18:30 UTC, AlenaKarp commented on Assets/Scripts/UI/ExchangeWindowItem.cs
> +                SetInteractable(true);
SetInteractable(amount > 0) 

Amount - наружу выдает данные, amount для приватной работы

2023-10-11 18:30 UTC, AlenaKarp commented on Assets/Scripts/UI/ExchangeWindowItem.cs
> +                background.sprite = inActiveSprite;
очепятка в interactabLe

Вот тут, если я правильно поняла, можно воспользоваться полем не sprite, а overrideSprite.
Его суть в том, что у нас по дефолту прям в префабе в спрайте будет перетащен спрайт inActiveSprite
А тут в методе можно просто прописать
background.overrideSprite = interactable == true ? activeSprite : null;

2023-10-18 18:42 UTC, MrDoctor-666 commented on Assets/Scripts/UI/ExchangeWindowItem.cs
> +                background.sprite = inActiveSprite;
а не оч понимаю, мы ж их постоянно меняем, и там в какой-то момент по идее будет не inActiveSprite, а activeSprite? и тогда надо наооборот будет оверрайдить? а о а о а

2023-10-18 18:45 UTC, MrDoctor-666 commented on Assets/Scripts/UI/ExchangeWindow.cs
> +        [SerializeField] private Image finalGetImage;
сделаль

2023-10-18 18:45 UTC, MrDoctor-666 commented on Assets/Scripts/UI/ExchangeWindow.cs
> +                        downItem.SetInteractable(false);
сделаль

2023-10-18 18:46 UTC, MrDoctor-666 commented on Assets/Scripts/UI/ExchangeWindow.cs
> +                finalSpendImage.sprite = upItemSelected.resourceImage.sprite;
сделаль плюс-минус так

2023-10-18 18:46 UTC, MrDoctor-666 commented on Assets/Scripts/UI/ExchangeWindow.cs
> +            finalSpendImage.sprite = null;
сделаль

2023-10-18 18:46 UTC, MrDoctor-666 commented on Assets/Scripts/UI/ExchangeWindowItem.cs
> +                SetInteractable(true);
сделаль

2023-10-18 18:53 UTC, MrDoctor-666 commented on Assets/Scripts/UI/ExchangeWindowItem.cs
> +                background.sprite = inActiveSprite;
вопрос снят, я почитала документацию хвхвх

2023-10-18 19:01 UTC, MrDoctor-666 commented on Assets/Scripts/UI/ExchangeWindow.cs
> +            amountSelection.GetComponentInChildren<TextMeshProUGUI>().text = (amountSelection.value).ToString();
сделаль

2023-10-18 19:50 UTC, AlenaKarp requested changes

2023-10-18 19:50 UTC, AlenaKarp commented on Assets/Scripts/UI/ExchangeWindow.cs
>                  upItemSelected = item;
Вынести в метод

2023-10-18 19:50 UTC, AlenaKarp commented on Assets/Scripts/UI/ExchangeWindow.cs
> +                item.SetInteractable(false);
Вынести в метод, который выше

2023-10-18 19:50 UTC, AlenaKarp commented on Assets/Scripts/UI/ExchangeWindow.cs
> +            amountSelection.GetComponentInChildren<TextMeshProUGUI>().text = (amountSelection.value).ToString();
А компонент то все еще получаешь
amountSelectionText.text = (amountSelection.value).ToString();

2023-10-25 18:11 UTC, MrDoctor-666 commented on Assets/Scripts/UI/ExchangeWindow.cs
> +            amountSelection.GetComponentInChildren<TextMeshProUGUI>().text = (amountSelection.value).ToString();
лоханулась конечно, но теперь поправила

2023-10-30 19:18 UTC, AlenaKarp approved these changes

2023-10-30 19:18 UTC, AlenaKarp commented on Assets/Art/UI_our/UI_fonts.png
Ето в проекте быть не должно

2023-10-30 19:18 UTC, merged