fix doubled resources bug
Ku6epnec/ZombieFarm pull request #68
Opened 2023-12-10 21:38 UTC by MrDoctor-666

2023-12-10 22:38 UTC, AlenaKarp requested changes

2023-12-10 22:38 UTC, AlenaKarp commented on Assets/Scenes/anyaloc 1.unity
Только на сцене они были сломаны?

2023-12-10 22:38 UTC, AlenaKarp commented on Assets/Scripts/UI/ProgressBar.cs
> +    internal event Action<float> OnRefreshProgress = (lostProgress) => { };
Зачем он internal? Из того что вижу ток в этом классе юзается? Если да, то private
А вообще помнится, что там проблема была в том, что зомбя дважды сдыхал или тип того, и надо было все на события перевесить как раз за этим. В целом если оно в этом виде работает и проблем не имеет - то ок, но как будто проблему ет не решает нифига

2023-12-11 19:57 UTC, MrDoctor-666 commented on Assets/Scripts/UI/ProgressBar.cs
> +    internal event Action<float> OnRefreshProgress = (lostProgress) => { };
так чегось, решает же
он отписывается от ивента рефрешить прогресс, когда заканчивает выполнение, поэтому вызывается разочек
я просто не могу вспомнить, как ты предалагала ивенты намутить?

2023-12-11 19:59 UTC, MrDoctor-666 commented on Assets/Scenes/anyaloc 1.unity
там на сцене отдельно лежат префабы goat и cage, связь надо было прокинуть одному из другого

2023-12-11 20:29 UTC, AlenaKarp commented on Assets/Scenes/anyaloc 1.unity
А что до второй сцены леса? Вопрос к этому, там не над?

2023-12-11 20:31 UTC, AlenaKarp commented on Assets/Scripts/UI/ProgressBar.cs
> +    internal event Action<float> OnRefreshProgress = (lostProgress) => { };
Тада вопрос остаётся об internal только

2024-01-10 20:27 UTC, AlenaKarp approved these changes

2024-01-10 20:29 UTC, merged