resources addition display
Ku6epnec/ZombieFarm pull request #94
Opened 2024-05-19 19:54 UTC by MrDoctor-666

2024-05-29 17:45 UTC, AlenaKarp requested changes

2024-05-29 17:45 UTC, AlenaKarp commented on Assets/Scripts/UI/ExchangeWindow.cs
> +        private void CheckOptions(LinkToResource obj, int amountChanged = 0)
Ай, не надо вот так, лучше там где вызывается явно укажи что 0

2024-05-29 17:45 UTC, AlenaKarp commented on Assets/Scripts/UI/ExchangeWindowItem.cs
> +        public void UpdateResourceAmount(LinkToResource _, int amountChanged = 0)
Мне кажется или amountChanged не используется?

2024-05-29 17:45 UTC, AlenaKarp commented on Assets/Scripts/UI/ResourceAdditionDisplay.cs
> +            DisplayResource(resource.resource, resource.amount, item);
`resource.resource` извините, а это точно ресурс? хахахах
Назови в ресурсе это поле просто link

2024-05-29 17:45 UTC, AlenaKarp commented on Assets/Scripts/UI/ResourceList.cs
> +        private void UpdateUI(LinkToResource linkToResource, int amount = 0)
Сейм как с верхним

2024-06-13 19:38 UTC, MrDoctor-666 commented on Assets/Scripts/UI/ExchangeWindowItem.cs
> +        public void UpdateResourceAmount(LinkToResource _, int amountChanged = 0)
тут да, но там просто ивент теперь стал с amountChanged, а он мне нужен (в ResourceAdditionDisplay), чтобы отображать только полученные ресурсы в всплывающем окне

было бы хорошо сделать какие-нибудь типы при получении ресурса, но хз, как будто для этого много перелопачивать придется, так чт решила пока так

2024-06-17 17:25 UTC, AlenaKarp approved these changes

2024-06-17 17:25 UTC, merged